//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type Member = $ModelResult<$Schema, "Member">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
export type Plan = $ModelResult<$Schema, "Plan">;
export type Auth = $TypeDefResult<$Schema, "Auth">;
